// Windissect recovered ABI metadata — DO NOT EDIT.
// Portable across C++17, C++20, C++23, and C++26 draft modes.
#pragma once
#include <cstddef>
#include <cstdint>

namespace windissect_abi {
struct TypeLayout { const char* name; std::uint64_t size; const char* kind; };
struct FieldLayout { const char* owner; const char* name; std::uint32_t type_index; std::uint64_t offset; bool is_static; };
struct FieldObservation { const char* owner; const char* suggested_name; std::uint64_t offset; std::uint32_t width; const char* access; std::uint32_t evidence_rva; const char* evidence_symbol; const char* confidence; };
struct BaseLayout { const char* derived; const char* base; std::int64_t offset; bool is_virtual; const char* evidence; const char* confidence; };
struct VTableLayout { const char* name; std::uint32_t rva; std::uint32_t slots; const char* evidence; const char* confidence; };
struct VTableSlotLayout { std::uint32_t table_rva; std::uint32_t slot; std::uint32_t target_rva; const char* target_id; const char* target_name; bool ambiguous; std::int32_t this_adjustment; };

inline constexpr TypeLayout types[] = {
    {".?AVbad_alloc@std@@", 0ULL, "class"},
    {".?AVbad_array_new_length@std@@", 0ULL, "class"},
    {".?AVexception@std@@", 0ULL, "class"},
    {".?AVtype_info@@", 0ULL, "class"},
    {"ATL", 0ULL, "layout-evidence"},
    {"ATL::CRegKey", 0ULL, "layout-evidence"},
    {"CallerIdentity", 0ULL, "layout-evidence"},
    {"MbaeHashCalculator", 0ULL, "layout-evidence"},
    {"std::bad_alloc", 0ULL, "layout-evidence"},
    {"std::bad_array_new_length", 0ULL, "layout-evidence"},
    {"std::exception", 0ULL, "layout-evidence"},
    {"type_info", 0ULL, "layout-evidence"},
    {"wil", 0ULL, "layout-evidence"},
    {"wil::details", 0ULL, "layout-evidence"},
    {"wil::details::in1diag3", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::handle_null_resource_policy<int (__cdecl *)(void *), int (__cdecl CloseHandle::*)(void *)> >", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<unsigned short *, void (__cdecl *)(void *), void (__cdecl CoTaskMemFree::*)(unsigned short *), struct wistd::integral_constant<uint64_t, 0>, unsigned short *, unsigned short *, 0, std::nullptr_t> >", 0ULL, "layout-evidence"},
    {"wil::details_abi", 0ULL, "layout-evidence"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", 0ULL, "layout-evidence"},
    {"wil::details_abi::SemaphoreValue", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalData", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalFailureInfo", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalStorage<class wil::details::ThreadFailureCallbackHolder *>", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalStorage<struct wil::details_abi::ThreadLocalData>", 0ULL, "layout-evidence"},
    {"wil::last_error_context", 0ULL, "layout-evidence"},
    {"wil::unique_any_t<class wil::details::unique_storage<struct wil::details::handle_null_resource_policy<int (__cdecl *)(void *), int (__cdecl CloseHandle::*)(void *)> > >", 0ULL, "layout-evidence"},
    {"wil::unique_any_t<class wil::details::unique_storage<struct wil::details::resource_policy<unsigned short *, void (__cdecl *)(void *), void (__cdecl CoTaskMemFree::*)(unsigned short *), struct wistd::integral_constant<uint64_t, 0>, unsigned short *, unsigned short *, 0, std::nullptr_t> > >", 0ULL, "layout-evidence"},
    {"wistd", 0ULL, "layout-evidence"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", 0ULL, "layout-evidence"},
    {nullptr, 0, nullptr},
};
inline constexpr std::size_t type_count = (sizeof(types) / sizeof(types[0])) - 1;
inline constexpr FieldLayout fields[] = {
    {nullptr, nullptr, 0, 0, false},
};
inline constexpr std::size_t field_count = (sizeof(fields) / sizeof(fields[0])) - 1;
inline constexpr FieldObservation field_observations[] = {
    {"ATL::CRegKey", nullptr, 0ULL, 8U, "read", 0x9210U, "?Close@CRegKey@ATL@@QEAAJXZ", "likely"},
    {"ATL::CRegKey", nullptr, 0ULL, 8U, "write", 0x9210U, "?Close@CRegKey@ATL@@QEAAJXZ", "likely"},
    {"ATL::CRegKey", nullptr, 0ULL, 8U, "read", 0x95F0U, "?SetStringValue@CRegKey@ATL@@QEAAJPEBG0K@Z", "likely"},
    {"ATL::CRegKey", nullptr, 0ULL, 8U, "write", 0xE180U, "?Create@CRegKey@ATL@@QEAAJPEAUHKEY__@@PEBGPEAGKKPEAU_SECURITY_ATTRIBUTES@@PEAK@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 0ULL, 1U, "read", 0x6B20U, "?GetHashHexString@MbaeHashCalculator@@QEBAPEBGXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 0ULL, 1U, "read", 0x6C40U, "?Calculate@MbaeHashCalculator@@QEAAJPEAG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 0ULL, 1U, "read", 0x6E30U, "?Initialize@MbaeHashCalculator@@QEAAJXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 0ULL, 1U, "write", 0x6E30U, "?Initialize@MbaeHashCalculator@@QEAAJXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 0ULL, 1U, "write", 0x7050U, "??0MbaeHashCalculator@@QEAA@PEBG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 0ULL, 1U, "write", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 64ULL, 2U, "write", 0x7050U, "??0MbaeHashCalculator@@QEAA@PEBG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 72ULL, 8U, "read", 0x6C40U, "?Calculate@MbaeHashCalculator@@QEAAJPEAG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 72ULL, 8U, "read", 0x6E30U, "?Initialize@MbaeHashCalculator@@QEAAJXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 72ULL, 8U, "write", 0x7050U, "??0MbaeHashCalculator@@QEAA@PEBG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 72ULL, 8U, "read", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 72ULL, 8U, "write", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 80ULL, 4U, "read", 0x6C40U, "?Calculate@MbaeHashCalculator@@QEAAJPEAG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 80ULL, 4U, "read", 0x6E30U, "?Initialize@MbaeHashCalculator@@QEAAJXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 80ULL, 4U, "write", 0x7050U, "??0MbaeHashCalculator@@QEAA@PEBG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 88ULL, 8U, "read", 0x6C40U, "?Calculate@MbaeHashCalculator@@QEAAJPEAG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 88ULL, 8U, "write", 0x6E30U, "?Initialize@MbaeHashCalculator@@QEAAJXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 88ULL, 8U, "write", 0x7050U, "??0MbaeHashCalculator@@QEAA@PEBG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 88ULL, 8U, "read", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 88ULL, 8U, "write", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 96ULL, 4U, "read", 0x6B20U, "?GetHashHexString@MbaeHashCalculator@@QEBAPEBGXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 96ULL, 4U, "read", 0x6C40U, "?Calculate@MbaeHashCalculator@@QEAAJPEAG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 96ULL, 4U, "read", 0x6E30U, "?Initialize@MbaeHashCalculator@@QEAAJXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 96ULL, 4U, "write", 0x7050U, "??0MbaeHashCalculator@@QEAA@PEBG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 104ULL, 8U, "read", 0x6B20U, "?GetHashHexString@MbaeHashCalculator@@QEBAPEBGXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 104ULL, 8U, "read", 0x6C40U, "?Calculate@MbaeHashCalculator@@QEAAJPEAG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 104ULL, 8U, "write", 0x6E30U, "?Initialize@MbaeHashCalculator@@QEAAJXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 104ULL, 8U, "write", 0x7050U, "??0MbaeHashCalculator@@QEAA@PEBG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 104ULL, 8U, "read", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 104ULL, 8U, "write", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 112ULL, 8U, "read", 0x6B20U, "?GetHashHexString@MbaeHashCalculator@@QEBAPEBGXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 112ULL, 8U, "read", 0x6C40U, "?Calculate@MbaeHashCalculator@@QEAAJPEAG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 112ULL, 8U, "write", 0x6E30U, "?Initialize@MbaeHashCalculator@@QEAAJXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 112ULL, 8U, "write", 0x7050U, "??0MbaeHashCalculator@@QEAA@PEBG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 112ULL, 8U, "read", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 112ULL, 8U, "write", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 120ULL, 8U, "read", 0x6C40U, "?Calculate@MbaeHashCalculator@@QEAAJPEAG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 120ULL, 8U, "write", 0x7050U, "??0MbaeHashCalculator@@QEAA@PEBG@Z", "likely"},
    {"MbaeHashCalculator", nullptr, 120ULL, 8U, "read", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"MbaeHashCalculator", nullptr, 120ULL, 8U, "write", 0x84F0U, "?Cleanup@MbaeHashCalculator@@AEAAXXZ", "likely"},
    {"std::bad_alloc", nullptr, 0ULL, 8U, "write", 0xA81CU, "??0bad_alloc@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::bad_alloc", nullptr, 0ULL, 8U, "write", 0xA860U, "??0bad_alloc@std@@QEAA@XZ", "likely"},
    {"std::bad_alloc", nullptr, 8ULL, 16U, "write", 0xA81CU, "??0bad_alloc@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::bad_alloc", nullptr, 8ULL, 8U, "write", 0xA860U, "??0bad_alloc@std@@QEAA@XZ", "likely"},
    {"std::bad_alloc", nullptr, 16ULL, 8U, "read-write", 0xA860U, "??0bad_alloc@std@@QEAA@XZ", "likely"},
    {"std::bad_array_new_length", nullptr, 0ULL, 8U, "write", 0xA884U, "??0bad_array_new_length@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::bad_array_new_length", nullptr, 0ULL, 8U, "write", 0xA8C8U, "??0bad_array_new_length@std@@QEAA@XZ", "likely"},
    {"std::bad_array_new_length", nullptr, 0ULL, 8U, "write", 0xA924U, "??1bad_array_new_length@std@@UEAA@XZ", "likely"},
    {"std::bad_array_new_length", nullptr, 8ULL, 16U, "write", 0xA884U, "??0bad_array_new_length@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::bad_array_new_length", nullptr, 8ULL, 8U, "write", 0xA8C8U, "??0bad_array_new_length@std@@QEAA@XZ", "likely"},
    {"std::bad_array_new_length", nullptr, 16ULL, 8U, "read-write", 0xA8C8U, "??0bad_array_new_length@std@@QEAA@XZ", "likely"},
    {"std::exception", nullptr, 0ULL, 8U, "write", 0xA8ECU, "??0exception@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::exception", nullptr, 0ULL, 8U, "write", 0xA940U, "??_Gexception@std@@UEAAPEAXI@Z", "likely"},
    {"std::exception", nullptr, 8ULL, 16U, "write", 0xA8ECU, "??0exception@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::exception", nullptr, 8ULL, 8U, "read", 0xA9E0U, "?what@exception@std@@UEBAPEBDXZ", "likely"},
    {"type_info", nullptr, 0ULL, 8U, "write", 0xA770U, "??_Gtype_info@@UEAAPEAXI@Z", "likely"},
    {"wil", nullptr, 0ULL, 2U, "read", 0x10994U, "?GetFailureLogString@wil@@YAJPEAG_KAEBUFailureInfo@1@@Z", "likely"},
    {"wil::details", nullptr, 0ULL, 1U, "read", 0xE990U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 0ULL, 2U, "write", 0x11650U, "?LogStringPrintf@details@wil@@YAPEAGPEAGPEBG1ZZ", "likely"},
    {"wil::details", nullptr, 4ULL, 4U, "read-write", 0xE990U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 8ULL, 4U, "read", 0xE990U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 8ULL, 4U, "read", 0x120F8U, "?WilFailFast@details@wil@@YAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 16ULL, 4U, "write", 0xE990U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 24ULL, 8U, "read", 0xE990U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 56ULL, 8U, "read", 0xE990U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 64ULL, 2U, "read", 0xE990U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 64ULL, 4U, "read", 0x120F8U, "?WilFailFast@details@wil@@YAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 128ULL, 8U, "read", 0xE990U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 136ULL, 8U, "read", 0x120F8U, "?WilFailFast@details@wil@@YAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details::unique_storage<struct wil::details::handle_null_resource_policy<int (__cdecl *)(void *), int (__cdecl CloseHandle::*)(void *)> >", nullptr, 0ULL, 8U, "read", 0xE700U, "??1?$unique_storage@U?$handle_null_resource_policy@P6AHPEAX@Z$1?CloseHandle@@YAH0@Z@details@wil@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<unsigned short *, void (__cdecl *)(void *), void (__cdecl CoTaskMemFree::*)(unsigned short *), struct wistd::integral_constant<uint64_t, 0>, unsigned short *, unsigned short *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0xE72CU, "??1?$unique_storage@U?$resource_policy@PEAGP6AXPEAX@Z$1?CoTaskMemFree@@YAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAGPEAG$0A@$$T@details@wil@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<unsigned short *, void (__cdecl *)(void *), void (__cdecl CoTaskMemFree::*)(unsigned short *), struct wistd::integral_constant<uint64_t, 0>, unsigned short *, unsigned short *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0xEE5CU, "?reset@?$unique_storage@U?$resource_policy@PEAGP6AXPEAX@Z$1?CoTaskMemFree@@YAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAGPEAG$0A@$$T@details@wil@@@details@wil@@QEAAXPEAG@Z", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<unsigned short *, void (__cdecl *)(void *), void (__cdecl CoTaskMemFree::*)(unsigned short *), struct wistd::integral_constant<uint64_t, 0>, unsigned short *, unsigned short *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "write", 0xEE5CU, "?reset@?$unique_storage@U?$resource_policy@PEAGP6AXPEAX@Z$1?CoTaskMemFree@@YAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAGPEAG$0A@$$T@details@wil@@@details@wil@@QEAAXPEAG@Z", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "read", 0x11924U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "write", 0x11924U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "read", 0x11924U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "write", 0x11924U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "read", 0x11924U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 8ULL, 8U, "read", 0x11C70U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 16ULL, 4U, "read", 0x11C70U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "read", 0x105ECU, "?Clear@ThreadLocalData@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "write", 0x105ECU, "?Clear@ThreadLocalData@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "read", 0x11C70U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "write", 0x11C70U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "read", 0x11C70U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 2U, "read", 0x105ECU, "?Clear@ThreadLocalData@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 4U, "write", 0x105ECU, "?Clear@ThreadLocalData@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 4U, "write", 0x11C70U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 2U, "read", 0x11C70U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 34ULL, 2U, "read", 0x11C70U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 34ULL, 2U, "write", 0x11C70U, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 4ULL, 4U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 8ULL, 4U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 16ULL, 8U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 24ULL, 2U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 26ULL, 1U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 32ULL, 8U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 40ULL, 8U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 48ULL, 8U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 56ULL, 8U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 64ULL, 8U, "read", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 64ULL, 8U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 64ULL, 8U, "read", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 72ULL, 8U, "read", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 72ULL, 8U, "write", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::details_abi::ThreadLocalFailureInfo", nullptr, 72ULL, 8U, "read", 0x11AD0U, "?Set@ThreadLocalFailureInfo@details_abi@wil@@QEAAXAEBUFailureInfo@3@I@Z", "likely"},
    {"wil::last_error_context", nullptr, 0ULL, 1U, "write", 0xE6BCU, "??0last_error_context@wil@@QEAA@XZ", "likely"},
    {"wil::last_error_context", nullptr, 0ULL, 1U, "read", 0xE750U, "??1last_error_context@wil@@QEAA@XZ", "likely"},
    {"wil::last_error_context", nullptr, 4ULL, 4U, "write", 0xE6BCU, "??0last_error_context@wil@@QEAA@XZ", "likely"},
    {"wil::last_error_context", nullptr, 4ULL, 4U, "read", 0xE750U, "??1last_error_context@wil@@QEAA@XZ", "likely"},
    {"wistd", nullptr, 0ULL, 8U, "read", 0xFC68U, "??$?8XUprocess_heap_deleter@wil@@@wistd@@YA_NAEBV?$unique_ptr@XUprocess_heap_deleter@wil@@@0@$$T@Z", "likely"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", nullptr, 0ULL, 8U, "write", 0xFC58U, "??$?0$00X@?$unique_ptr@XUprocess_heap_deleter@wil@@@wistd@@QEAA@PEAX@Z", "likely"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", nullptr, 0ULL, 8U, "read", 0x10388U, "??1?$unique_ptr@XUprocess_heap_deleter@wil@@@wistd@@QEAA@XZ", "likely"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", nullptr, 0ULL, 8U, "read-write", 0x10388U, "??1?$unique_ptr@XUprocess_heap_deleter@wil@@@wistd@@QEAA@XZ", "likely"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", nullptr, 0ULL, 8U, "read", 0x122C8U, "?release@?$unique_ptr@XUprocess_heap_deleter@wil@@@wistd@@QEAAPEAXXZ", "likely"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", nullptr, 0ULL, 8U, "read-write", 0x122C8U, "?release@?$unique_ptr@XUprocess_heap_deleter@wil@@@wistd@@QEAAPEAXXZ", "likely"},
    {nullptr, nullptr, 0, 0, nullptr, 0, nullptr, nullptr},
};
inline constexpr std::size_t field_observation_count = (sizeof(field_observations) / sizeof(field_observations[0])) - 1;
inline constexpr BaseLayout bases[] = {
    {".?AVbad_alloc@std@@", ".?AVbad_alloc@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVbad_alloc@std@@", ".?AVexception@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVbad_array_new_length@std@@", ".?AVbad_array_new_length@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVbad_array_new_length@std@@", ".?AVbad_alloc@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVbad_array_new_length@std@@", ".?AVexception@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVexception@std@@", ".?AVexception@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVtype_info@@", ".?AVtype_info@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {nullptr, nullptr, -1, false, nullptr, nullptr},
};
inline constexpr std::size_t base_count = (sizeof(bases) / sizeof(bases[0])) - 1;
inline constexpr VTableLayout vtables[] = {
    {"const type_info::`vftable'", 0x142A8U, 1U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::exception::`vftable'", 0x142B8U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::bad_alloc::`vftable'", 0x142D0U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::bad_array_new_length::`vftable'", 0x142E8U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {nullptr, 0, 0, nullptr, nullptr},
};
inline constexpr std::size_t vtable_count = (sizeof(vtables) / sizeof(vtables[0])) - 1;
inline constexpr VTableSlotLayout vtable_slots[] = {
    {0x142A8U, 0U, 0xA770U, nullptr, nullptr, true, 0},
    {0x142B8U, 0U, 0xA940U, nullptr, nullptr, true, 0},
    {0x142B8U, 1U, 0xA9E0U, "?what@exception@std@@UEBAPEBDXZ", "public: virtual char const * __cdecl std::exception::what(void) const", false, 0},
    {0x142D0U, 0U, 0xA940U, nullptr, nullptr, true, 0},
    {0x142D0U, 1U, 0xA9E0U, nullptr, nullptr, true, 0},
    {0x142E8U, 0U, 0xA940U, nullptr, nullptr, true, 0},
    {0x142E8U, 1U, 0xA9E0U, nullptr, nullptr, true, 0},
    {0, 0, 0, nullptr, nullptr, true, 0},
};
inline constexpr std::size_t vtable_slot_count = (sizeof(vtable_slots) / sizeof(vtable_slots[0])) - 1;
}
